parameters:
   pcas_base_url: "https://ecas.ec.europa.eu/cas"

services:
 pcas.pcas_factory:
   class: OpenEuropa\pcas\PCasFactory
   public: true
   arguments:
    - '@session'
    - '%pcas_base_url%'