parameters:
   pcas_base_url: "http://127.0.0.1:8001"

services:
   pcas.pcas_factory:
     class: OpenEuropa\pcas\PCasFactory
     public: true
     arguments:
      - '@session'
      - '%pcas_base_url%'