parameters:
   pcas_base_url: "http://pcas-server:8080/demo-server/public"

services:
   pcas.pcas_factory:
     class: OpenEuropa\pcas\PCasFactory
     public: true
     arguments:
      - '@session'
      - '%pcas_base_url%'